export class SubscribercoRequest{
    name:string;
    address:string;
    managerName:string;
    managerEmail:string;
    managerPhone:string;
    managerPassword:string;
    ceoPassword:string;
    ceoName:string;
    ceoEmail:string;
    ceoPhone:string;
    status:string;
    minMonthBilling:string;
    perUserRate:number;
    code:string;
    role:string;
    adminRole:string;
    operation:string;
}